### ISSUE TITLE
[Bug] Errors when running "gendocs" command

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptHub/SkriptHubDocsTool#4]
Hey.

So today I tried to run the "gendocs" command, and this is what I get:
(I know the error says the plugin's version is 1.3, but Im running the 1.4 version on the releases tab)

```
[13:13:07 INFO]: [Skript Hub Docs Tool] Generating Docs
[13:13:07 INFO]: /gendocs
[13:13:07 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[13:13:07 WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[13:13:07 WARN]: 	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[13:13:07 WARN]: 	at java.base/java.lang.reflect.Field.get(Field.java:425)
[13:13:07 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.GenerateSyntax$Companion.getEntiresFromSkriptEventInfo(GenerateSyntax.kt:256)
[13:13:07 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.GenerateSyntax$Companion.generateSyntaxFromEvent(GenerateSyntax.kt:70)
[13:13:07 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.BuildDocs.run(BuildDocs.kt:53)
[13:13:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:13:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:13:07 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:13:07 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:13:07 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:13:07 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:13:07 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[13:13:08 WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[13:13:08 WARN]: 	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[13:13:08 WARN]: 	at java.base/java.lang.reflect.Field.get(Field.java:425)
[13:13:08 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.GenerateSyntax$Companion.getEntiresFromSkriptElementInfo(GenerateSyntax.kt:206)
[13:13:08 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.GenerateSyntax$Companion.generateSyntaxFromSyntaxElementInfo(GenerateSyntax.kt:102)
[13:13:08 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.BuildDocs.run(BuildDocs.kt:65)
[13:13:08 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:13:08 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:13:08 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:13:08 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:13:08 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:13:08 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:13:08 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
[13:13:08 WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[13:13:08 WARN]: 	at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
[13:13:08 WARN]: 	at java.base/java.lang.reflect.Field.get(Field.java:425)
[13:13:08 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.GenerateSyntax$Companion.getEntiresFromSkriptElementInfo(GenerateSyntax.kt:206)
[13:13:08 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.GenerateSyntax$Companion.generateSyntaxFromSyntaxElementInfo(GenerateSyntax.kt:102)
[13:13:08 WARN]: 	at skripthubdocstool-1.4.jar//net.skripthub.docstool.documentation.BuildDocs.run(BuildDocs.kt:73)
[13:13:08 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:13:08 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:13:08 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:13:08 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:13:08 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:13:08 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:13:08 WARN]: [Skript Hub Docs Tool] Plugin SkriptHubDocsTool v1.3 generated an exception while executing task 10
java.lang.NoClassDefFoundError: ch/njol/skript/lang/Loop
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.skripthub.docstool.documentation.GenerateSyntax$Companion.getEntiresFromSkriptElementInfo(GenerateSyntax.kt:200) ~[skripthubdocstool-1.4.jar:?]
	at net.skripthub.docstool.documentation.GenerateSyntax$Companion.generateSyntaxFromSyntaxElementInfo(GenerateSyntax.kt:102) ~[skripthubdocstool-1.4.jar:?]
	at net.skripthub.docstool.documentation.GenerateSyntax$Companion.generateSyntaxFromExpression(GenerateSyntax.kt:108) ~[skripthubdocstool-1.4.jar:?]
	at net.skripthub.docstool.documentation.BuildDocs.run$lambda-0(BuildDocs.kt:88) ~[skripthubdocstool-1.4.jar:?]
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003) ~[?:?]
	at net.skripthub.docstool.documentation.BuildDocs.run(BuildDocs.kt:84) ~[skripthubdocstool-1.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-51]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-51]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.lang.Loop
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 15 more
```

**Comment by eyesniper2** [comment]
This should be fixed as of version 1.5
