### ISSUE TITLE
Skript 2.8.1

### ISSUE THREAD

**Issue by SkJsonTeam** [SkriptHub/SkriptHubDocsTool#6]
```
[23:06:49 INFO]: /gendocs
[23:06:50 WARN]: [Skript Hub Docs Tool] Plugin SkriptHubDocsTool v1.5 generated an exception while executing task 15
java.lang.NoSuchFieldError: c
        at net.skripthub.docstool.documentation.BuildDocs.getAddon(BuildDocs.kt:287) ~[skripthubdocstool-1.5.jar:?]
        at net.skripthub.docstool.documentation.BuildDocs.run(BuildDocs.kt:48) ~[skripthubdocstool-1.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>
```

**Comment by eyesniper2** [comment]
This should be fixed in the 1.6 Update.
