### ISSUE TITLE
/gendocs causes java.lang.NoSuchFieldError: elementClass

### ISSUE THREAD

**Issue by takejohn** [SkriptHub/SkriptHubDocsTool#7]
/gendocs doesn't work with my environment.
This is the stack trace.
It implies the field `SyntaxElementInfo#elementClass` doesn't exist.
```
> gendocs
[01:13:30 INFO]: [Skript Hub Docs Tool] Generating Docs
[01:13:30 INFO]: /gendocs
[01:13:31 WARN]: [Skript Hub Docs Tool] Plugin SkriptHubDocsTool v1.6 generated an exception while executing task 13
java.lang.NoSuchFieldError: elementClass
        at net.skripthub.docstool.documentation.GenerateSyntax$Companion.getEntriesFromSkriptEventInfo(GenerateSyntax.kt:318) ~[skripthubdocstool-1.6.jar:?]
        at net.skripthub.docstool.documentation.GenerateSyntax$Companion.generateSyntaxFromEvent(GenerateSyntax.kt:72) ~[skripthubdocstool-1.6.jar:?]
        at net.skripthub.docstool.documentation.BuildDocs.run(BuildDocs.kt:52) ~[skripthubdocstool-1.6.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2124]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

/skript info:
```
> skript info
[01:14:06 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[01:14:06 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[01:14:06 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[01:14:06 INFO]: [Skript] Server Version: git-Purpur-2124 (MC: 1.20.4)
[01:14:06 INFO]: [Skript] Skript Version: 2.7.3 (skriptlang-github)
[01:14:06 INFO]: [Skript] Installed Skript Addons:
[01:14:06 INFO]: [Skript]  - Bask v0.1.0-SNAPSHOT
[01:14:06 INFO]: [Skript] Installed dependencies: None
```

**Comment by eyesniper2** [comment]
Hey thanks for the PR, but it looks like the main issue is that you are running SkriptHubDocsTool v1.6 with Skript 2.7.3. 1.6 only support Skript 2.8 and up.

You can either use SkriptHubDocsTool 1.5 with your current Skript version, or update your Skript to 2.8+.

I accepted the PR since the calling pattern you submitted is better and was recommended by the Skript team. Those changes will be rolled into 1.7 with support for structures. Thanks for all the help!
